export const apartments = [
  { name: "BEL. FREIRE 2510 - 9A - CABA", requiresKey: true },
  { name: "BEL. MOLDES 2032 - 17", requiresKey: true },
  { name: "BEL. QUESADA 1595", requiresKey: true },
  { name: "BEL. VIRREY LORETO 3077 - 1D", requiresKey: true },
  { name: "MIC. VIAMONTE 480 7.26", requiresKey: true },
  { name: "NUÑ. Arcos 3251 - 3E", requiresKey: true },
  { name: "NUÑ. ZAPIOLA 3535 - 1.107", requiresKey: true },
  { name: "NUÑ. ZAPIOLA 3535 - 2.216", requiresKey: true },
  { name: "PAL. BULNES 1844 - 17", requiresKey: true },
  { name: "PAL. FITZROY 1406 - 9no", requiresKey: true },
  { name: "PAL. FITZROY 2077 - 4.3", requiresKey: false },
  { name: "PAL. FITZROY 2077 - 4.4", requiresKey: false },
  { name: "PAL. FITZROY 2077 - 5.3 - CABA", requiresKey: false },
  { name: "PAL. FITZROY 2077 - 7.2 - CABA", requiresKey: false },
  { name: "PAL. FITZROY 2077 - 9.01", requiresKey: false },
  { name: "PAL. GODOY CRUZ 2530 - 204", requiresKey: false },
  { name: "PAL. GODOY CRUZ 2530 - 304", requiresKey: false },
  { name: "PAL. GORRITI 4050 - 404", requiresKey: true },
  { name: "PAL. MEDRANO 1066 - 1.E", requiresKey: true },
  { name: "PAL. ORO - 103 - CABA", requiresKey: false },
  { name: "PAL. ORO - 303", requiresKey: false },
  { name: "PAL. ORO - 304 - CABA", requiresKey: false },
  { name: "PAL. PALACIO ALCORTA", requiresKey: false },
  { name: "PAL. PALACIO ALCORTA 109", requiresKey: false },
  { name: "PAL. PARAGUAY 2468 - 4D", requiresKey: true },
  { name: "PAL. PARAGUAY 2590 - 1.C", requiresKey: true },
  { name: "PAL. Paraguay 5257 - 8B", requiresKey: false },
  { name: "PAL. SAN BENITO DE PALERMO - 1674 6.", requiresKey: true },
  { name: "PAL. SOLER 6026 - 6.A", requiresKey: false },
  { name: "REC. AYACUCHO 2040 - 9.35", requiresKey: true },
  { name: "REC. VICENTE LÓPEZ 1933 - 6.42 - CABA", requiresKey: true },
  { name: "REC. VICENTE LÓPEZ 1933 - 6.47", requiresKey: true },
  { name: "RET. ESMERALDA 1061 (P.PAZ) - 906", requiresKey: false },
  { name: "RET. QUARTIER STUDIO - 102", requiresKey: false },
  { name: "Sargento cabral 876", requiresKey: true },
  { name: "ST. CASEROS 445 - 16.P3 - SAN TELMO", requiresKey: true },
  { name: "ST. GIUFFRA 344 - Depto 8", requiresKey: true },
  { name: "VC.VELASCO1032.8.1", requiresKey: true },
] as const;
